name: Publish to Registry
on:    
  push:
    tags:
      - '*'
jobs:
  update:
    runs-on: ubuntu-latest
    container: node:10.16-jessie
    steps:
    - name: Checkout
      uses: actions/checkout@master
      

    - name: echo version
      run: echo ${GITHUB_REF:10}
  